### ISSUE TITLE
MVI 单Activity不能实现侧滑返回上一个页面的样子吧？

### ISSUE THREAD

**Issue by mtj956052456** [shenzhen2017/wanandroid-compose#1]
![image](https://user-images.githubusercontent.com/24516875/144370432-336c204f-017a-4f71-a0f6-b4f303379acc.png)

**Comment by RicardoJiang** [comment]
侧滑返回现在不是很多手机自带的吗，由于是单Activity,也就是返回到Navigation Graph的上一个，当然可以返回，但不会有你的示意图这种一半展示的效果。
